var RestoUrls = new Array();
RestoUrls= [
'https://www.relaischateaux.com/fr/france/restaurant/gastronomique-cote-d-or-la-bussiere-sur-ouche',
'https://www.relaischateaux.com/fr/france/restaurant/anne-de-bretagne-loire-atlantique-la-plaine-sur-mer',
'https://www.relaischateaux.com/fr/france/restaurant/assiette-champenoise-restaurant',
'https://www.relaischateaux.com/fr/france/bon-a-savoir-crocodile',
'https://www.relaischateaux.com/fr/france/restaurant/le-cinq-rhone-alpes-la-clusaz',
'https://www.relaischateaux.com/fr/france/experience/un-diner-particulier-dans-la-suite-du-chef-aubergedelile',
'https://www.relaischateaux.com/fr/france/restaurant/auberge-des-glazicks-restaurant',
'https://www.relaischateaux.com/fr/france/restaurant/auberge-des-templiers-loiret-boismorand',
'https://www.relaischateaux.com/fr/france/restaurant/la-table-du-connetable-oise-chantilly',
'https://www.relaischateaux.com/fr/france/restaurant/l-oustau-de-baumaniere-bouches-du-rhone-les-baux-de-provence',
'https://www.relaischateaux.com/fr/france/restaurant/le-yachtman-finistere-roscoff',
'https://www.relaischateaux.com/fr/france/restaurant/les-pecheurs-alpes-maritimes-cap-d-antibes',
'https://www.relaischateaux.com/fr/france/restaurant/le-1800-morbihan-bangor',
'https://www.relaischateaux.com/fr/france/restaurant/cazaudehore-yvelines-saint-germain-en-laye',
'https://www.relaischateaux.com/fr/france/restaurant/chateau-cordeillan-bages-gironde-pauillac',
'https://www.relaischateaux.com/fr/france/restaurant/restaurant-lalique-peyraguey-bommes',
'https://www.relaischateaux.com/fr/france/restaurant/la-salle-des-gardes-rhone-alpes-bagnols',
'https://www.relaischateaux.com/fr/france/restaurant/le-jardin-de-benjamin-restaurant',
'https://www.relaischateaux.com/fr/france/restaurant/chateau-de-codignat-puy-de-dome-bort-l-etang',
'https://www.relaischateaux.com/fr/france/restaurant/restaurant-chateau-de-courcelles-aisne-courcelles-sur-vesle',
'https://www.relaischateaux.com/fr/france/restaurant/la-cedraie-vienne-curzay-sur-vonne',
'https://www.relaischateaux.com/fr/france/restaurant/le-verdurier-drudas',
'https://www.relaischateaux.com/fr/france/restaurant/l-orangerie-bouches-du-rhone-le-puy-sainte-reparade',
'https://www.relaischateaux.com/fr/france/restaurant/chateau-de-germigney-jura-port-lesney',
'https://www.relaischateaux.com/fr/france/restaurant/la-chevre-d-or-alpes-maritimes-eze-village',
'https://www.relaischateaux.com/fr/france/restaurant/chateau-de-locguenole-morbihan-kervignac',
'https://www.relaischateaux.com/fr/france/restaurant/le-dueze-lot-mercues',
'https://www.relaischateaux.com/fr/france/restaurant/chateau-de-mirambeau-charente-maritime-mirambeau',
'https://www.relaischateaux.com/fr/france/restaurant/chateau-de-montreuil-pas-de-calais-montreuil',
'https://www.relaischateaux.com/fr/france/restaurant/cote-gastronomique-maine-et-loire-briollay',
'https://www.relaischateaux.com/fr/france/restaurant/le-castel-indre-et-loire-noizay',
'https://www.relaischateaux.com/fr/france/restaurant/restaurant-du-chatelain-pyrenees-orientales-prades',
'https://www.relaischateaux.com/fr/france/restaurant/roche-aigue-drome-rochegude',
'https://www.relaischateaux.com/fr/france/restaurant/la-palmeraie-la-croix-valmer',
'https://www.relaischateaux.com/fr/france/restaurant/chateau-de-la-treyne-lot-lacave',
'https://www.relaischateaux.com/fr/france/restaurant/domaine-des-avenieres-haute-savoie-cruseilles',
'https://www.relaischateaux.com/fr/france/restaurant/chateau-d-adomenil-meurthe-et-moselle-luneville',
'https://www.relaischateaux.com/fr/france/restaurant/chateau-d-audrieu-calvados-audrieu',
'https://www.relaischateaux.com/fr/france/restaurant/la-table-nord-lille',
'https://www.relaischateaux.com/fr/france/restaurant/le-gourmet-vaucluse-gargas',
'https://www.relaischateaux.com/fr/france/restaurant/le-parc-marne-reims',
'https://www.relaischateaux.com/fr/france/restaurant/domaine-de-rochevilaine-morbihan-billiers'
]

module.exports = RestoUrls;